### ISSUE TITLE
I can't follow the guide, unless I changed the namespace to hello.

### ISSUE THREAD

**Issue by rubenjoy** [pedestal/pedestal-docs#138]
I tried to follow hello-world pedestal guide in this link http://pedestal.io/guides/hello-world
All the steps are correct except the namespace.

after load the hello namespace, I need to switch namespace to hello before continue following the guide. If I didn't change the namespace - still in user namespace, the `hello/response-hello` was not there. So changing the namespace seems solved my issue. 

I admitted I'm total noobs here, so maybe somebody can give me an explanation  here.
btw I use clojure 1.10.1.536.

**Comment by ddeaguiar** [comment]
Hi @rubenjoy, sorry to hear you ran into some trouble with the guide. You don't need to switch to the `hello` namespace in order to print and execute the `hello/respond-hello` function. As the guide demonstrates, you `require` the `hello` namespace first, then reference the functions defined within it by using the fully qualified name which, in this case, would be `hello/respond-hello`.

Refer to the [Namespace](https://clojure.org/reference/namespaces) and [require](https://clojuredocs.org/clojure.core/require) docs for details.

Thanks for trying out Pedestal!
