### ISSUE TITLE
Add section about hot reload to "Developing at the REPL" guide

### ISSUE THREAD

**Issue by mtnygard** [pedestal/pedestal-docs#71]
It's a common question. 

- How to get new handlers used without restarting the REPL?
- How to get routes reloaded?

**Comment by ohpauleez** [comment]
It's already mentioned in the "Starting and Stopping" section.  Perhaps it just needs to be bolded?

Pedestal's default dev-mode picks up changes as soon as they're re-required via the REPL (either in your editor or with `:reload-all` at the REPL itself).  The beginner guides suggest using an atom only because they're written as if someone was typing everything into the REPL (without files/namespaces)

**Comment by mtnygard** [comment]
Thanks, I knew it was in there somewhere... just couldn't find it!
