### ISSUE TITLE
todo-api: potential for the use of list-view and list-item-view to be made uniform

### ISSUE THREAD

**Issue by pdkovacs** [pedestal/pedestal-docs#86]
`list-view` does its work in the `:enter` phase of the route handling, while `list-item-view` does it in the `:leave` phase. This difference entails that these two interceptors are placed in different orders relative to `db-interceptor ` in the "list viewer" and "list-item viewer" routes.

Is there any particular reason for this difference? Is there anything preventing both interceptors from doing their work in, for example, the `:leave` phase and being uniformly placed before `db-interceptor`?

**Comment by ddeaguiar** [comment]
The difference is due to the type of work that that `list-vew` interceptor does compared to the `list-item-view` interceptor. The `list-view` interceptor is responsible for looking up an existing list-item from the database based on the `:list-id` path parameter. It requires the `:database` assoc'd to the context by the `db-interceptor`'s `:enter` fn to do its work. In contrast, the `list-item-view` interceptor is responsible for assoc'ing the created list item to the context via the `:result` key. This must occur _after_ the `db-interceptor`'s `:leave` implementation executes because that is where the data is transacted to the database. We don't have a created result to render until it exists in the database.

This example demonstrates how responsibilities can be distributed across interceptors and how common responsibilities can be shared. While I'm a proponent of the segregation of responsibilities demonstrated in the _Your first API [guide](http://pedestal.io/guides/your-first-api), I don't commonly see it in the wild.
